### ISSUE TITLE
Builded Transport Package is broken

### ISSUE THREAD

**Issue by tjventurini** [BobRay/MyComponent#32]
# what did I try to do?

I just finished the first big milestone in my package development, so I tried to install the package on an other modx installation by copying the package transport zip to its core/packages directory. But when I now look for local packages from within the package manager, I get an 500 error like the following.

    [Sat Oct 22 17:37:19.003719 2016] [:error] [pid 24196] [client 192.168.33.1:54336] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in /var/www/html/core/xpdo/compression/pclzip.lib.php on line 190, referer: http://modxvmtest.dev/manager/?a=workspaces

# what did I found out already?

It took me some while to figure out, that some files and folders are missing in the transport package. Eg in the modCategory folder in my development installation (where everything works) I have `modCategory/0` and `modCategory/1` folders, in the given transport package I only have `modCategory/1`.

# environments

Using [modxvm](https://github.com/tjventurini/modxvm) as development environment with modx 2.5.1 and mycomponent 3.2.2. The modx installation I wanted to install the package to is also a modxvm instance.

# thank you :)

**Comment by tjventurini** [comment]
Finaly I was able to isolate the error and so I found out, that the video file I had in my package was the Issue. I don't know why, but somehow the package manager could not handle it ... after changing the folder name from `videos` to `video` and replacing the mp4 file everything worked just fine :)

**Comment by BobRay** [comment]
Thanks for reporting back. I can't think of any reason why that would be a problem since MC just zips up all the files it finds.

**Comment by tjventurini** [comment]
Jup its a strange error. I hoped for some whisdom from the community on how to prevent such an error. But hey since, you are here, could you take a look at my next problem? Its issue #33 thx a lot :)
